# Generated by Django 3.0.1 on 2019-12-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('priority', models.IntegerField()),
                ('flag', models.IntegerField()),
                ('expireDate', models.DateTimeField()),
                ('createDate', models.DateTimeField()),
            ],
        ),
    ]
